// Generated by CoffeeScript 1.4.0
(function() {

  (function($) {
    return $.extend({
      ooQuery: function(params, opts) {
        var default_params, timed_out, timer, validDate;
        if (!(params != null)) {
          throw 'parameters required';
        }
        if (!(opts != null)) {
          throw 'options required';
        }
        default_params = {
          autoParse: true,
          versionMinor: '1'
        };
        $.extend(default_params, params);
        if (!(default_params.id != null)) {
          throw 'id parameter required';
        }
        if (!(default_params.aid != null)) {
          throw 'aid parameter required';
        }
        if (!(default_params.startDate != null)) {
          throw 'startDate parameter required';
        }
        if (!(default_params.endDate != null)) {
          throw 'endDate parameter required';
        }
        validDate = function(value) {
          return !/Invalid|NaN/.test(new Date(value).toString());
        };
        if (!validDate(default_params.startDate)) {
          throw 'startDate is not valid date';
        }
        if (!validDate(default_params.endDate)) {
          throw 'endDate is not valid date';
        }
        if (!(default_params.metrics != null)) {
          throw 'metrics parameter required';
        }
        timed_out = false;
        if (opts.timeout != null) {
          timer = setTimeout(function() {
            timed_out = true;
            if (opts.error != null) {
              return opts.error();
            }
          }, opts.timeout);
        }
        return $.getJSON('https://oocharts.org/s/api/v2?callback=?', default_params, function(response) {
          if (timer != null) {
            clearTimeout(timer);
          }
          if (!timed_out && (opts.success != null)) {
            return opts.success(response.data);
          }
        });
      }
    });
  })(jQuery);

}).call(this);
